/**
 * UltraStar Wingman
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AddToWishListModel model module.
 * @module model/AddToWishListModel
 * @version 1.1.0
 */
class AddToWishListModel {
    /**
     * Constructs a new <code>AddToWishListModel</code>.
     * @alias module:model/AddToWishListModel
     * @param songId {String} The universal ID of the song.
     */
    constructor(songId) { 
        
        AddToWishListModel.initialize(this, songId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, songId) { 
        obj['song_id'] = songId;
    }

    /**
     * Constructs a <code>AddToWishListModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AddToWishListModel} obj Optional instance to populate.
     * @return {module:model/AddToWishListModel} The populated <code>AddToWishListModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddToWishListModel();

            if (data.hasOwnProperty('song_id')) {
                obj['song_id'] = ApiClient.convertToType(data['song_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AddToWishListModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AddToWishListModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AddToWishListModel.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['song_id'] && !(typeof data['song_id'] === 'string' || data['song_id'] instanceof String)) {
            throw new Error("Expected the field `song_id` to be a primitive type in the JSON string but got " + data['song_id']);
        }

        return true;
    }


}

AddToWishListModel.RequiredProperties = ["song_id"];

/**
 * The universal ID of the song.
 * @member {String} song_id
 */
AddToWishListModel.prototype['song_id'] = undefined;






export default AddToWishListModel;

