/**
 * UltraStar Wingman
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PermissionPatchModel from './PermissionPatchModel';

/**
 * The PermissionsPatchModel model module.
 * @module model/PermissionsPatchModel
 * @version 2.0.0
 */
class PermissionsPatchModel {
    /**
     * Constructs a new <code>PermissionsPatchModel</code>.
     * @alias module:model/PermissionsPatchModel
     */
    constructor() { 
        
        PermissionsPatchModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PermissionsPatchModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PermissionsPatchModel} obj Optional instance to populate.
     * @return {module:model/PermissionsPatchModel} The populated <code>PermissionsPatchModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PermissionsPatchModel();

            if (data.hasOwnProperty('permissions')) {
                obj['permissions'] = ApiClient.convertToType(data['permissions'], {'String': PermissionPatchModel});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PermissionsPatchModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PermissionsPatchModel</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Permissions to patch.
 * @member {Object.<String, module:model/PermissionPatchModel>} permissions
 */
PermissionsPatchModel.prototype['permissions'] = undefined;






export default PermissionsPatchModel;

