/**
 * UltraStar Wingman
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AccessLevel from './AccessLevel';
import PermissionModel from './PermissionModel';

/**
 * The PermissionsModel model module.
 * @module model/PermissionsModel
 * @version 1.1.0
 */
class PermissionsModel {
    /**
     * Constructs a new <code>PermissionsModel</code>.
     * @alias module:model/PermissionsModel
     */
    constructor() { 
        
        PermissionsModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PermissionsModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PermissionsModel} obj Optional instance to populate.
     * @return {module:model/PermissionsModel} The populated <code>PermissionsModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PermissionsModel();

            if (data.hasOwnProperty('access_levels')) {
                obj['access_levels'] = ApiClient.convertToType(data['access_levels'], [AccessLevel]);
            }
            if (data.hasOwnProperty('permissions')) {
                obj['permissions'] = ApiClient.convertToType(data['permissions'], {'String': PermissionModel});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PermissionsModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PermissionsModel</code>.
     */
    static validateJSON(data) {
        if (data['access_levels']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['access_levels'])) {
                throw new Error("Expected the field `access_levels` to be an array in the JSON data but got " + data['access_levels']);
            }
            // validate the optional field `access_levels` (array)
            for (const item of data['access_levels']) {
                AccessLevel.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * All available access levels.
 * @member {Array.<module:model/AccessLevel>} access_levels
 */
PermissionsModel.prototype['access_levels'] = undefined;

/**
 * All available permissions.
 * @member {Object.<String, module:model/PermissionModel>} permissions
 */
PermissionsModel.prototype['permissions'] = undefined;






export default PermissionsModel;

