/**
 * UltraStar Wingman
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PermissionModel from './PermissionModel';

/**
 * The PermissionsPatchResponseModel model module.
 * @module model/PermissionsPatchResponseModel
 * @version 1.1.0
 */
class PermissionsPatchResponseModel {
    /**
     * Constructs a new <code>PermissionsPatchResponseModel</code>.
     * @alias module:model/PermissionsPatchResponseModel
     */
    constructor() { 
        
        PermissionsPatchResponseModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PermissionsPatchResponseModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PermissionsPatchResponseModel} obj Optional instance to populate.
     * @return {module:model/PermissionsPatchResponseModel} The populated <code>PermissionsPatchResponseModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PermissionsPatchResponseModel();

            if (data.hasOwnProperty('permissions')) {
                obj['permissions'] = ApiClient.convertToType(data['permissions'], {'String': PermissionModel});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PermissionsPatchResponseModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PermissionsPatchResponseModel</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Patched permissions.
 * @member {Object.<String, module:model/PermissionModel>} permissions
 */
PermissionsPatchResponseModel.prototype['permissions'] = undefined;






export default PermissionsPatchResponseModel;

