/**
 * UltraStar Wingman
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PlayerList model module.
 * @module model/PlayerList
 * @version 1.1.0
 */
class PlayerList {
    /**
     * Constructs a new <code>PlayerList</code>.
     * @alias module:model/PlayerList
     */
    constructor() { 
        
        PlayerList.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PlayerList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PlayerList} obj Optional instance to populate.
     * @return {module:model/PlayerList} The populated <code>PlayerList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PlayerList();

            if (data.hasOwnProperty('players')) {
                obj['players'] = ApiClient.convertToType(data['players'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PlayerList</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PlayerList</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['players'])) {
            throw new Error("Expected the field `players` to be an array in the JSON data but got " + data['players']);
        }

        return true;
    }


}



/**
 * List of player names.
 * @member {Array.<String>} players
 */
PlayerList.prototype['players'] = undefined;






export default PlayerList;

