/**
 * UltraStar Wingman
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RegisteredPlayerModel from './RegisteredPlayerModel';
import UnregisteredPlayerModel from './UnregisteredPlayerModel';

/**
 * The PlayersModel model module.
 * @module model/PlayersModel
 * @version 2.0.0
 */
class PlayersModel {
    /**
     * Constructs a new <code>PlayersModel</code>.
     * @alias module:model/PlayersModel
     */
    constructor() { 
        
        PlayersModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PlayersModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PlayersModel} obj Optional instance to populate.
     * @return {module:model/PlayersModel} The populated <code>PlayersModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PlayersModel();

            if (data.hasOwnProperty('registered')) {
                obj['registered'] = ApiClient.convertToType(data['registered'], [RegisteredPlayerModel]);
            }
            if (data.hasOwnProperty('unregistered')) {
                obj['unregistered'] = ApiClient.convertToType(data['unregistered'], [UnregisteredPlayerModel]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PlayersModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PlayersModel</code>.
     */
    static validateJSON(data) {
        if (data['registered']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['registered'])) {
                throw new Error("Expected the field `registered` to be an array in the JSON data but got " + data['registered']);
            }
            // validate the optional field `registered` (array)
            for (const item of data['registered']) {
                RegisteredPlayerModel.validateJSON(item);
            };
        }
        if (data['unregistered']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['unregistered'])) {
                throw new Error("Expected the field `unregistered` to be an array in the JSON data but got " + data['unregistered']);
            }
            // validate the optional field `unregistered` (array)
            for (const item of data['unregistered']) {
                UnregisteredPlayerModel.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * List of registered players.
 * @member {Array.<module:model/RegisteredPlayerModel>} registered
 */
PlayersModel.prototype['registered'] = undefined;

/**
 * List of unregistered players.
 * @member {Array.<module:model/UnregisteredPlayerModel>} unregistered
 */
PlayersModel.prototype['unregistered'] = undefined;






export default PlayersModel;

