/**
 * UltraStar Wingman
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RegisteredPlayerModel from './RegisteredPlayerModel';

/**
 * The RegisteredPlayersModel model module.
 * @module model/RegisteredPlayersModel
 * @version 1.1.0
 */
class RegisteredPlayersModel {
    /**
     * Constructs a new <code>RegisteredPlayersModel</code>.
     * @alias module:model/RegisteredPlayersModel
     */
    constructor() { 
        
        RegisteredPlayersModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RegisteredPlayersModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RegisteredPlayersModel} obj Optional instance to populate.
     * @return {module:model/RegisteredPlayersModel} The populated <code>RegisteredPlayersModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RegisteredPlayersModel();

            if (data.hasOwnProperty('registered')) {
                obj['registered'] = ApiClient.convertToType(data['registered'], [RegisteredPlayerModel]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RegisteredPlayersModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RegisteredPlayersModel</code>.
     */
    static validateJSON(data) {
        if (data['registered']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['registered'])) {
                throw new Error("Expected the field `registered` to be an array in the JSON data but got " + data['registered']);
            }
            // validate the optional field `registered` (array)
            for (const item of data['registered']) {
                RegisteredPlayerModel.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * List of registered players.
 * @member {Array.<module:model/RegisteredPlayerModel>} registered
 */
RegisteredPlayersModel.prototype['registered'] = undefined;






export default RegisteredPlayersModel;

