/**
 * UltraStar Wingman
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Score model module.
 * @module model/Score
 * @version 2.0.0
 */
class Score {
    /**
     * Constructs a new <code>Score</code>.
     * @alias module:model/Score
     */
    constructor() { 
        
        Score.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Score</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Score} obj Optional instance to populate.
     * @return {module:model/Score} The populated <code>Score</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Score();

            if (data.hasOwnProperty('player_id')) {
                obj['player_id'] = ApiClient.convertToType(data['player_id'], 'String');
            }
            if (data.hasOwnProperty('player')) {
                obj['player'] = ApiClient.convertToType(data['player'], 'String');
            }
            if (data.hasOwnProperty('registered')) {
                obj['registered'] = ApiClient.convertToType(data['registered'], 'Boolean');
            }
            if (data.hasOwnProperty('score')) {
                obj['score'] = ApiClient.convertToType(data['score'], 'Number');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Score</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Score</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['player_id'] && !(typeof data['player_id'] === 'string' || data['player_id'] instanceof String)) {
            throw new Error("Expected the field `player_id` to be a primitive type in the JSON string but got " + data['player_id']);
        }
        // ensure the json data is a string
        if (data['player'] && !(typeof data['player'] === 'string' || data['player'] instanceof String)) {
            throw new Error("Expected the field `player` to be a primitive type in the JSON string but got " + data['player']);
        }

        return true;
    }


}



/**
 * The player id.
 * @member {String} player_id
 */
Score.prototype['player_id'] = undefined;

/**
 * The player name.
 * @member {String} player
 */
Score.prototype['player'] = undefined;

/**
 * If the player is registered.
 * @member {Boolean} registered
 */
Score.prototype['registered'] = undefined;

/**
 * The score of the performance.
 * @member {Number} score
 */
Score.prototype['score'] = undefined;

/**
 * The date of the performance.
 * @member {Number} date
 */
Score.prototype['date'] = undefined;






export default Score;

