/**
 * UltraStar Wingman
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SessionModel model module.
 * @module model/SessionModel
 * @version 2.0.0
 */
class SessionModel {
    /**
     * Constructs a new <code>SessionModel</code>.
     * @alias module:model/SessionModel
     */
    constructor() { 
        
        SessionModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SessionModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SessionModel} obj Optional instance to populate.
     * @return {module:model/SessionModel} The populated <code>SessionModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SessionModel();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('start_time')) {
                obj['start_time'] = ApiClient.convertToType(data['start_time'], 'Number');
            }
            if (data.hasOwnProperty('end_time')) {
                obj['end_time'] = ApiClient.convertToType(data['end_time'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SessionModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SessionModel</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * The session ID.
 * @member {Number} id
 */
SessionModel.prototype['id'] = undefined;

/**
 * The start time of the session.
 * @member {Number} start_time
 */
SessionModel.prototype['start_time'] = undefined;

/**
 * The end time of the session.
 * @member {Number} end_time
 */
SessionModel.prototype['end_time'] = undefined;






export default SessionModel;

