/**
 * UltraStar Wingman
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Song model module.
 * @module model/Song
 * @version 1.1.0
 */
class Song {
    /**
     * Constructs a new <code>Song</code>.
     * @alias module:model/Song
     * @param artist {String} 
     * @param downloaded {Boolean} 
     * @param edition {String} 
     * @param golden {Boolean} 
     * @param id {String} 
     * @param language {String} 
     * @param rating {Number} 
     * @param title {String} 
     * @param views {Number} 
     */
    constructor(artist, downloaded, edition, golden, id, language, rating, title, views) { 
        
        Song.initialize(this, artist, downloaded, edition, golden, id, language, rating, title, views);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, artist, downloaded, edition, golden, id, language, rating, title, views) { 
        obj['artist'] = artist;
        obj['downloaded'] = downloaded;
        obj['edition'] = edition;
        obj['golden'] = golden;
        obj['id'] = id;
        obj['language'] = language;
        obj['rating'] = rating;
        obj['title'] = title;
        obj['views'] = views;
    }

    /**
     * Constructs a <code>Song</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Song} obj Optional instance to populate.
     * @return {module:model/Song} The populated <code>Song</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Song();

            if (data.hasOwnProperty('artist')) {
                obj['artist'] = ApiClient.convertToType(data['artist'], 'String');
            }
            if (data.hasOwnProperty('downloaded')) {
                obj['downloaded'] = ApiClient.convertToType(data['downloaded'], 'Boolean');
            }
            if (data.hasOwnProperty('edition')) {
                obj['edition'] = ApiClient.convertToType(data['edition'], 'String');
            }
            if (data.hasOwnProperty('golden')) {
                obj['golden'] = ApiClient.convertToType(data['golden'], 'Boolean');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('language')) {
                obj['language'] = ApiClient.convertToType(data['language'], 'String');
            }
            if (data.hasOwnProperty('rating')) {
                obj['rating'] = ApiClient.convertToType(data['rating'], 'Number');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('views')) {
                obj['views'] = ApiClient.convertToType(data['views'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Song</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Song</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Song.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['artist'] && !(typeof data['artist'] === 'string' || data['artist'] instanceof String)) {
            throw new Error("Expected the field `artist` to be a primitive type in the JSON string but got " + data['artist']);
        }
        // ensure the json data is a string
        if (data['edition'] && !(typeof data['edition'] === 'string' || data['edition'] instanceof String)) {
            throw new Error("Expected the field `edition` to be a primitive type in the JSON string but got " + data['edition']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['language'] && !(typeof data['language'] === 'string' || data['language'] instanceof String)) {
            throw new Error("Expected the field `language` to be a primitive type in the JSON string but got " + data['language']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }

        return true;
    }


}

Song.RequiredProperties = ["artist", "downloaded", "edition", "golden", "id", "language", "rating", "title", "views"];

/**
 * @member {String} artist
 */
Song.prototype['artist'] = undefined;

/**
 * @member {Boolean} downloaded
 */
Song.prototype['downloaded'] = undefined;

/**
 * @member {String} edition
 */
Song.prototype['edition'] = undefined;

/**
 * @member {Boolean} golden
 */
Song.prototype['golden'] = undefined;

/**
 * @member {String} id
 */
Song.prototype['id'] = undefined;

/**
 * @member {String} language
 */
Song.prototype['language'] = undefined;

/**
 * @member {Number} rating
 */
Song.prototype['rating'] = undefined;

/**
 * @member {String} title
 */
Song.prototype['title'] = undefined;

/**
 * @member {Number} views
 */
Song.prototype['views'] = undefined;






export default Song;

