/**
 * UltraStar Wingman
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SpotifyAuthorize model module.
 * @module model/SpotifyAuthorize
 * @version 2.0.0
 */
class SpotifyAuthorize {
    /**
     * Constructs a new <code>SpotifyAuthorize</code>.
     * @alias module:model/SpotifyAuthorize
     * @param code {String} The code from the spotify callback.
     */
    constructor(code) { 
        
        SpotifyAuthorize.initialize(this, code);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, code) { 
        obj['code'] = code;
    }

    /**
     * Constructs a <code>SpotifyAuthorize</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SpotifyAuthorize} obj Optional instance to populate.
     * @return {module:model/SpotifyAuthorize} The populated <code>SpotifyAuthorize</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SpotifyAuthorize();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SpotifyAuthorize</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SpotifyAuthorize</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SpotifyAuthorize.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['code'] && !(typeof data['code'] === 'string' || data['code'] instanceof String)) {
            throw new Error("Expected the field `code` to be a primitive type in the JSON string but got " + data['code']);
        }

        return true;
    }


}

SpotifyAuthorize.RequiredProperties = ["code"];

/**
 * The code from the spotify callback.
 * @member {String} code
 */
SpotifyAuthorize.prototype['code'] = undefined;






export default SpotifyAuthorize;

