/**
 * UltraStar Wingman
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SpotifyPlaylist from './SpotifyPlaylist';

/**
 * The SpotifyPlaylists model module.
 * @module model/SpotifyPlaylists
 * @version 2.0.0
 */
class SpotifyPlaylists {
    /**
     * Constructs a new <code>SpotifyPlaylists</code>.
     * @alias module:model/SpotifyPlaylists
     * @param playlists {Array.<module:model/SpotifyPlaylist>} A list of Spotify playlists.
     */
    constructor(playlists) { 
        
        SpotifyPlaylists.initialize(this, playlists);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, playlists) { 
        obj['playlists'] = playlists;
    }

    /**
     * Constructs a <code>SpotifyPlaylists</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SpotifyPlaylists} obj Optional instance to populate.
     * @return {module:model/SpotifyPlaylists} The populated <code>SpotifyPlaylists</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SpotifyPlaylists();

            if (data.hasOwnProperty('playlists')) {
                obj['playlists'] = ApiClient.convertToType(data['playlists'], [SpotifyPlaylist]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SpotifyPlaylists</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SpotifyPlaylists</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SpotifyPlaylists.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['playlists']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['playlists'])) {
                throw new Error("Expected the field `playlists` to be an array in the JSON data but got " + data['playlists']);
            }
            // validate the optional field `playlists` (array)
            for (const item of data['playlists']) {
                SpotifyPlaylist.validateJSON(item);
            };
        }

        return true;
    }


}

SpotifyPlaylists.RequiredProperties = ["playlists"];

/**
 * A list of Spotify playlists.
 * @member {Array.<module:model/SpotifyPlaylist>} playlists
 */
SpotifyPlaylists.prototype['playlists'] = undefined;






export default SpotifyPlaylists;

