/**
 * UltraStar Wingman
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SpotifyAuthorizeUrl model module.
 * @module model/SpotifyAuthorizeUrl
 * @version 2.0.0
 */
class SpotifyAuthorizeUrl {
    /**
     * Constructs a new <code>SpotifyAuthorizeUrl</code>.
     * @alias module:model/SpotifyAuthorizeUrl
     * @param authorizeUrl {String} The url to access for the authorization code.
     */
    constructor(authorizeUrl) { 
        
        SpotifyAuthorizeUrl.initialize(this, authorizeUrl);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, authorizeUrl) { 
        obj['authorize_url'] = authorizeUrl;
    }

    /**
     * Constructs a <code>SpotifyAuthorizeUrl</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SpotifyAuthorizeUrl} obj Optional instance to populate.
     * @return {module:model/SpotifyAuthorizeUrl} The populated <code>SpotifyAuthorizeUrl</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SpotifyAuthorizeUrl();

            if (data.hasOwnProperty('authorize_url')) {
                obj['authorize_url'] = ApiClient.convertToType(data['authorize_url'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SpotifyAuthorizeUrl</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SpotifyAuthorizeUrl</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SpotifyAuthorizeUrl.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['authorize_url'] && !(typeof data['authorize_url'] === 'string' || data['authorize_url'] instanceof String)) {
            throw new Error("Expected the field `authorize_url` to be a primitive type in the JSON string but got " + data['authorize_url']);
        }

        return true;
    }


}

SpotifyAuthorizeUrl.RequiredProperties = ["authorize_url"];

/**
 * The url to access for the authorization code.
 * @member {String} authorize_url
 */
SpotifyAuthorizeUrl.prototype['authorize_url'] = undefined;






export default SpotifyAuthorizeUrl;

