/**
 * UltraStar Wingman
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SpotifySong from './SpotifySong';

/**
 * The SpotifyPlaylistItems model module.
 * @module model/SpotifyPlaylistItems
 * @version 2.0.0
 */
class SpotifyPlaylistItems {
    /**
     * Constructs a new <code>SpotifyPlaylistItems</code>.
     * @alias module:model/SpotifyPlaylistItems
     * @param limit {Number} The maximum number of items in the response.
     * @param offset {Number} The offset of the items returned.
     * @param total {Number} The total number of items available to return.
     * @param songs {Array.<module:model/SpotifySong>} A list of songs.
     */
    constructor(limit, offset, total, songs) { 
        
        SpotifyPlaylistItems.initialize(this, limit, offset, total, songs);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, limit, offset, total, songs) { 
        obj['limit'] = limit;
        obj['offset'] = offset;
        obj['total'] = total;
        obj['songs'] = songs;
    }

    /**
     * Constructs a <code>SpotifyPlaylistItems</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SpotifyPlaylistItems} obj Optional instance to populate.
     * @return {module:model/SpotifyPlaylistItems} The populated <code>SpotifyPlaylistItems</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SpotifyPlaylistItems();

            if (data.hasOwnProperty('limit')) {
                obj['limit'] = ApiClient.convertToType(data['limit'], 'Number');
            }
            if (data.hasOwnProperty('offset')) {
                obj['offset'] = ApiClient.convertToType(data['offset'], 'Number');
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('songs')) {
                obj['songs'] = ApiClient.convertToType(data['songs'], [SpotifySong]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SpotifyPlaylistItems</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SpotifyPlaylistItems</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SpotifyPlaylistItems.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['songs']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['songs'])) {
                throw new Error("Expected the field `songs` to be an array in the JSON data but got " + data['songs']);
            }
            // validate the optional field `songs` (array)
            for (const item of data['songs']) {
                SpotifySong.validateJSON(item);
            };
        }

        return true;
    }


}

SpotifyPlaylistItems.RequiredProperties = ["limit", "offset", "total", "songs"];

/**
 * The maximum number of items in the response.
 * @member {Number} limit
 */
SpotifyPlaylistItems.prototype['limit'] = undefined;

/**
 * The offset of the items returned.
 * @member {Number} offset
 */
SpotifyPlaylistItems.prototype['offset'] = undefined;

/**
 * The total number of items available to return.
 * @member {Number} total
 */
SpotifyPlaylistItems.prototype['total'] = undefined;

/**
 * A list of songs.
 * @member {Array.<module:model/SpotifySong>} songs
 */
SpotifyPlaylistItems.prototype['songs'] = undefined;






export default SpotifyPlaylistItems;

