/**
 * UltraStar Wingman
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SpotifyPlaylist model module.
 * @module model/SpotifyPlaylist
 * @version 2.0.0
 */
class SpotifyPlaylist {
    /**
     * Constructs a new <code>SpotifyPlaylist</code>.
     * @alias module:model/SpotifyPlaylist
     * @param id {String} The Spotify ID for the playlist.
     * @param name {String} The name of the playlist.
     * @param image {String} The url for the playlist image.
     */
    constructor(id, name, image) { 
        
        SpotifyPlaylist.initialize(this, id, name, image);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, image) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['image'] = image;
    }

    /**
     * Constructs a <code>SpotifyPlaylist</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SpotifyPlaylist} obj Optional instance to populate.
     * @return {module:model/SpotifyPlaylist} The populated <code>SpotifyPlaylist</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SpotifyPlaylist();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('image')) {
                obj['image'] = ApiClient.convertToType(data['image'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SpotifyPlaylist</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SpotifyPlaylist</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SpotifyPlaylist.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['image'] && !(typeof data['image'] === 'string' || data['image'] instanceof String)) {
            throw new Error("Expected the field `image` to be a primitive type in the JSON string but got " + data['image']);
        }

        return true;
    }


}

SpotifyPlaylist.RequiredProperties = ["id", "name", "image"];

/**
 * The Spotify ID for the playlist.
 * @member {String} id
 */
SpotifyPlaylist.prototype['id'] = undefined;

/**
 * The name of the playlist.
 * @member {String} name
 */
SpotifyPlaylist.prototype['name'] = undefined;

/**
 * The url for the playlist image.
 * @member {String} image
 */
SpotifyPlaylist.prototype['image'] = undefined;






export default SpotifyPlaylist;

