/**
 * UltraStar Wingman
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class UdEnum.
* @enum {}
* @readonly
*/
export default class UdEnum {
    
        /**
         * value: "asc"
         * @const
         */
        "asc" = "asc";

    
        /**
         * value: "desc"
         * @const
         */
        "desc" = "desc";

    

    /**
    * Returns a <code>UdEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/UdEnum} The enum <code>UdEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

