/**
 * UltraStar Wingman
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UltrastarWingmanState model module.
 * @module model/UltrastarWingmanState
 * @version 2.0.0
 */
class UltrastarWingmanState {
    /**
     * Constructs a new <code>UltrastarWingmanState</code>.
     * @alias module:model/UltrastarWingmanState
     */
    constructor() { 
        
        UltrastarWingmanState.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UltrastarWingmanState</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UltrastarWingmanState} obj Optional instance to populate.
     * @return {module:model/UltrastarWingmanState} The populated <code>UltrastarWingmanState</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UltrastarWingmanState();

            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'String');
            }
            if (data.hasOwnProperty('new_version')) {
                obj['new_version'] = ApiClient.convertToType(data['new_version'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UltrastarWingmanState</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UltrastarWingmanState</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['version'] && !(typeof data['version'] === 'string' || data['version'] instanceof String)) {
            throw new Error("Expected the field `version` to be a primitive type in the JSON string but got " + data['version']);
        }
        // ensure the json data is a string
        if (data['new_version'] && !(typeof data['new_version'] === 'string' || data['new_version'] instanceof String)) {
            throw new Error("Expected the field `new_version` to be a primitive type in the JSON string but got " + data['new_version']);
        }

        return true;
    }


}



/**
 * The current version of Ultrastar Wingman
 * @member {String} version
 */
UltrastarWingmanState.prototype['version'] = undefined;

/**
 * The new version if one is available
 * @member {String} new_version
 */
UltrastarWingmanState.prototype['new_version'] = undefined;






export default UltrastarWingmanState;

