/**
 * UltraStar Wingman
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserRead model module.
 * @module model/UserRead
 * @version 2.0.0
 */
class UserRead {
    /**
     * Constructs a new <code>UserRead</code>.
     * @alias module:model/UserRead
     * @param id {String} 
     * @param email {String} 
     * @param accessLevel {Number} 
     */
    constructor(id, email, accessLevel) { 
        
        UserRead.initialize(this, id, email, accessLevel);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, email, accessLevel) { 
        obj['id'] = id;
        obj['email'] = email;
        obj['access_level'] = accessLevel;
    }

    /**
     * Constructs a <code>UserRead</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserRead} obj Optional instance to populate.
     * @return {module:model/UserRead} The populated <code>UserRead</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserRead();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('is_active')) {
                obj['is_active'] = ApiClient.convertToType(data['is_active'], 'Boolean');
            }
            if (data.hasOwnProperty('is_superuser')) {
                obj['is_superuser'] = ApiClient.convertToType(data['is_superuser'], 'Boolean');
            }
            if (data.hasOwnProperty('is_verified')) {
                obj['is_verified'] = ApiClient.convertToType(data['is_verified'], 'Boolean');
            }
            if (data.hasOwnProperty('access_level')) {
                obj['access_level'] = ApiClient.convertToType(data['access_level'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserRead</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserRead</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UserRead.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }

        return true;
    }


}

UserRead.RequiredProperties = ["id", "email", "access_level"];

/**
 * @member {String} id
 */
UserRead.prototype['id'] = undefined;

/**
 * @member {String} email
 */
UserRead.prototype['email'] = undefined;

/**
 * @member {Boolean} is_active
 * @default true
 */
UserRead.prototype['is_active'] = true;

/**
 * @member {Boolean} is_superuser
 * @default false
 */
UserRead.prototype['is_superuser'] = false;

/**
 * @member {Boolean} is_verified
 * @default false
 */
UserRead.prototype['is_verified'] = false;

/**
 * @member {Number} access_level
 */
UserRead.prototype['access_level'] = undefined;






export default UserRead;

