/**
 * UltraStar Wingman
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WishModel from './WishModel';

/**
 * The WishlistModel model module.
 * @module model/WishlistModel
 * @version 2.0.0
 */
class WishlistModel {
    /**
     * Constructs a new <code>WishlistModel</code>.
     * @alias module:model/WishlistModel
     * @param wishes {Array.<module:model/WishModel>} 
     */
    constructor(wishes) { 
        
        WishlistModel.initialize(this, wishes);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, wishes) { 
        obj['wishes'] = wishes;
    }

    /**
     * Constructs a <code>WishlistModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WishlistModel} obj Optional instance to populate.
     * @return {module:model/WishlistModel} The populated <code>WishlistModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WishlistModel();

            if (data.hasOwnProperty('wishes')) {
                obj['wishes'] = ApiClient.convertToType(data['wishes'], [WishModel]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WishlistModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WishlistModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of WishlistModel.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['wishes']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['wishes'])) {
                throw new Error("Expected the field `wishes` to be an array in the JSON data but got " + data['wishes']);
            }
            // validate the optional field `wishes` (array)
            for (const item of data['wishes']) {
                WishModel.validateJSON(item);
            };
        }

        return true;
    }


}

WishlistModel.RequiredProperties = ["wishes"];

/**
 * @member {Array.<module:model/WishModel>} wishes
 */
WishlistModel.prototype['wishes'] = undefined;






export default WishlistModel;

