/**
 * UltraStar Wingman
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UltraStarWingman);
  }
}(this, function(expect, UltraStarWingman) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new UltraStarWingman.UserUpdate();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UserUpdate', function() {
    it('should create an instance of UserUpdate', function() {
      // uncomment below and update the code to test UserUpdate
      //var instance = new UltraStarWingman.UserUpdate();
      //expect(instance).to.be.a(UltraStarWingman.UserUpdate);
    });

    it('should have the property password (base name: "password")', function() {
      // uncomment below and update the code to test the property password
      //var instance = new UltraStarWingman.UserUpdate();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new UltraStarWingman.UserUpdate();
      //expect(instance).to.be();
    });

    it('should have the property isActive (base name: "is_active")', function() {
      // uncomment below and update the code to test the property isActive
      //var instance = new UltraStarWingman.UserUpdate();
      //expect(instance).to.be();
    });

    it('should have the property isSuperuser (base name: "is_superuser")', function() {
      // uncomment below and update the code to test the property isSuperuser
      //var instance = new UltraStarWingman.UserUpdate();
      //expect(instance).to.be();
    });

    it('should have the property isVerified (base name: "is_verified")', function() {
      // uncomment below and update the code to test the property isVerified
      //var instance = new UltraStarWingman.UserUpdate();
      //expect(instance).to.be();
    });

    it('should have the property accessLevel (base name: "access_level")', function() {
      // uncomment below and update the code to test the property accessLevel
      //var instance = new UltraStarWingman.UserUpdate();
      //expect(instance).to.be();
    });

  });

}));
