/**
 * UltraStar Wingman
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import HTTPValidationError from '../model/HTTPValidationError';
import PermissionsModel from '../model/PermissionsModel';
import PermissionsPatchModel from '../model/PermissionsPatchModel';
import PermissionsPatchResponseModel from '../model/PermissionsPatchResponseModel';

/**
* Permissions service.
* @module api/PermissionsApi
* @version 2.0.0
*/
export default class PermissionsApi {

    /**
    * Constructs a new PermissionsApi. 
    * @alias module:api/PermissionsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the apiPermissionsGetApiPermissionsGet operation.
     * @callback module:api/PermissionsApi~apiPermissionsGetApiPermissionsGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PermissionsModel} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all permissions
     * Gets all the permissions.
     * @param {module:api/PermissionsApi~apiPermissionsGetApiPermissionsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PermissionsModel}
     */
    apiPermissionsGetApiPermissionsGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PermissionsModel;
      return this.apiClient.callApi(
        '/api/permissions', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the apiPermissionsPatchApiPermissionsPatch operation.
     * @callback module:api/PermissionsApi~apiPermissionsPatchApiPermissionsPatchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PermissionsPatchResponseModel} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Patch data for permissions
     * Patch permissions.
     * @param {module:model/PermissionsPatchModel} permissionsPatchModel 
     * @param {module:api/PermissionsApi~apiPermissionsPatchApiPermissionsPatchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PermissionsPatchResponseModel}
     */
    apiPermissionsPatchApiPermissionsPatch(permissionsPatchModel, callback) {
      let postBody = permissionsPatchModel;
      // verify the required parameter 'permissionsPatchModel' is set
      if (permissionsPatchModel === undefined || permissionsPatchModel === null) {
        throw new Error("Missing the required parameter 'permissionsPatchModel' when calling apiPermissionsPatchApiPermissionsPatch");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PermissionsPatchResponseModel;
      return this.apiClient.callApi(
        '/api/permissions', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
