/**
 * UltraStar Wingman
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import UltrastarWingmanState from '../model/UltrastarWingmanState';

/**
* UltraStarWingman service.
* @module api/UltraStarWingmanApi
* @version 2.0.0
*/
export default class UltraStarWingmanApi {

    /**
    * Constructs a new UltraStarWingmanApi. 
    * @alias module:api/UltraStarWingmanApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the apiUwStateApiUwStateGet operation.
     * @callback module:api/UltraStarWingmanApi~apiUwStateApiUwStateGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/UltrastarWingmanState} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * The state of Ultrastar Wingman - new available version etc.
     * @param {module:api/UltraStarWingmanApi~apiUwStateApiUwStateGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/UltrastarWingmanState}
     */
    apiUwStateApiUwStateGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = UltrastarWingmanState;
      return this.apiClient.callApi(
        '/api/uw/state', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
