/**
 * UltraStar Wingman
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UltraStarWingman);
  }
}(this, function(expect, UltraStarWingman) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new UltraStarWingman.AuthApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AuthApi', function() {
    describe('authJwtLoginAuthJwtLoginPost', function() {
      it('should call authJwtLoginAuthJwtLoginPost successfully', function(done) {
        //uncomment below and update the code to test authJwtLoginAuthJwtLoginPost
        //instance.authJwtLoginAuthJwtLoginPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('authJwtLogoutAuthJwtLogoutPost', function() {
      it('should call authJwtLogoutAuthJwtLogoutPost successfully', function(done) {
        //uncomment below and update the code to test authJwtLogoutAuthJwtLogoutPost
        //instance.authJwtLogoutAuthJwtLogoutPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('registerRegisterAuthRegisterPost', function() {
      it('should call registerRegisterAuthRegisterPost successfully', function(done) {
        //uncomment below and update the code to test registerRegisterAuthRegisterPost
        //instance.registerRegisterAuthRegisterPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('resetForgotPasswordAuthForgotPasswordPost', function() {
      it('should call resetForgotPasswordAuthForgotPasswordPost successfully', function(done) {
        //uncomment below and update the code to test resetForgotPasswordAuthForgotPasswordPost
        //instance.resetForgotPasswordAuthForgotPasswordPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('resetResetPasswordAuthResetPasswordPost', function() {
      it('should call resetResetPasswordAuthResetPasswordPost successfully', function(done) {
        //uncomment below and update the code to test resetResetPasswordAuthResetPasswordPost
        //instance.resetResetPasswordAuthResetPasswordPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('verifyRequestTokenAuthRequestVerifyTokenPost', function() {
      it('should call verifyRequestTokenAuthRequestVerifyTokenPost successfully', function(done) {
        //uncomment below and update the code to test verifyRequestTokenAuthRequestVerifyTokenPost
        //instance.verifyRequestTokenAuthRequestVerifyTokenPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('verifyVerifyAuthVerifyPost', function() {
      it('should call verifyVerifyAuthVerifyPost successfully', function(done) {
        //uncomment below and update the code to test verifyVerifyAuthVerifyPost
        //instance.verifyVerifyAuthVerifyPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
