/**
 * UltraStar Wingman
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UltraStarWingman);
  }
}(this, function(expect, UltraStarWingman) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new UltraStarWingman.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('aliasRoutesScoresGet', function() {
      it('should call aliasRoutesScoresGet successfully', function(done) {
        //uncomment below and update the code to test aliasRoutesScoresGet
        //instance.aliasRoutesScoresGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('aliasRoutesSongsGet', function() {
      it('should call aliasRoutesSongsGet successfully', function(done) {
        //uncomment below and update the code to test aliasRoutesSongsGet
        //instance.aliasRoutesSongsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('aliasRoutesUsdbGet', function() {
      it('should call aliasRoutesUsdbGet successfully', function(done) {
        //uncomment below and update the code to test aliasRoutesUsdbGet
        //instance.aliasRoutesUsdbGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('aliasRoutesUsdbListGet', function() {
      it('should call aliasRoutesUsdbListGet successfully', function(done) {
        //uncomment below and update the code to test aliasRoutesUsdbListGet
        //instance.aliasRoutesUsdbListGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('aliasRoutesUserGet', function() {
      it('should call aliasRoutesUserGet successfully', function(done) {
        //uncomment below and update the code to test aliasRoutesUserGet
        //instance.aliasRoutesUserGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
