/**
 * UltraStar Wingman
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UltraStarWingman);
  }
}(this, function(expect, UltraStarWingman) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new UltraStarWingman.PlayersApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PlayersApi', function() {
    describe('apiPlayersAddApiPlayersPost', function() {
      it('should call apiPlayersAddApiPlayersPost successfully', function(done) {
        //uncomment below and update the code to test apiPlayersAddApiPlayersPost
        //instance.apiPlayersAddApiPlayersPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiPlayersApiPlayersGet', function() {
      it('should call apiPlayersApiPlayersGet successfully', function(done) {
        //uncomment below and update the code to test apiPlayersApiPlayersGet
        //instance.apiPlayersApiPlayersGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiPlayersSubmitApiPlayersSubmitPost', function() {
      it('should call apiPlayersSubmitApiPlayersSubmitPost successfully', function(done) {
        //uncomment below and update the code to test apiPlayersSubmitApiPlayersSubmitPost
        //instance.apiPlayersSubmitApiPlayersSubmitPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteNameApiPlayersDelete', function() {
      it('should call deleteNameApiPlayersDelete successfully', function(done) {
        //uncomment below and update the code to test deleteNameApiPlayersDelete
        //instance.deleteNameApiPlayersDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
