/**
 * UltraStar Wingman
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UltraStarWingman);
  }
}(this, function(expect, UltraStarWingman) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new UltraStarWingman.ScoresApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ScoresApi', function() {
    describe('apiScoresGetApiScoresGet', function() {
      it('should call apiScoresGetApiScoresGet successfully', function(done) {
        //uncomment below and update the code to test apiScoresGetApiScoresGet
        //instance.apiScoresGetApiScoresGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiScoresGetApiScoresSessionIdGet', function() {
      it('should call apiScoresGetApiScoresSessionIdGet successfully', function(done) {
        //uncomment below and update the code to test apiScoresGetApiScoresSessionIdGet
        //instance.apiScoresGetApiScoresSessionIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiSessionsGetApiSessionsGet', function() {
      it('should call apiSessionsGetApiSessionsGet successfully', function(done) {
        //uncomment below and update the code to test apiSessionsGetApiSessionsGet
        //instance.apiSessionsGetApiSessionsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
