/**
 * UltraStar Wingman
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UltraStarWingman);
  }
}(this, function(expect, UltraStarWingman) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new UltraStarWingman.WebsiteApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('WebsiteApi', function() {
    describe('avatarAvatarsAvatarGet', function() {
      it('should call avatarAvatarsAvatarGet successfully', function(done) {
        //uncomment below and update the code to test avatarAvatarsAvatarGet
        //instance.avatarAvatarsAvatarGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('downloadDownloadGet', function() {
      it('should call downloadDownloadGet successfully', function(done) {
        //uncomment below and update the code to test downloadDownloadGet
        //instance.downloadDownloadGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('indexGet', function() {
      it('should call indexGet successfully', function(done) {
        //uncomment below and update the code to test indexGet
        //instance.indexGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('playersPlayersGet', function() {
      it('should call playersPlayersGet successfully', function(done) {
        //uncomment below and update the code to test playersPlayersGet
        //instance.playersPlayersGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('scoresScoresGet', function() {
      it('should call scoresScoresGet successfully', function(done) {
        //uncomment below and update the code to test scoresScoresGet
        //instance.scoresScoresGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('songsSongsGet', function() {
      it('should call songsSongsGet successfully', function(done) {
        //uncomment below and update the code to test songsSongsGet
        //instance.songsSongsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
